language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO=Django==1.4.13
  - DJANGO=Django==1.5.8
  - DJANGO=Django==1.6.5
  - DJANGO=https://github.com/django/django/archive/stable/1.7.x.zip
install:
  - pip install -q $DJANGO --use-mirrors
script:
  - python runtests.py

matrix:
  exclude:
    - env: DJANGO=Django==1.4.13
      python: "3.3"
    - env: DJANGO=Django==1.4.13
      python: "3.4"
